### ISSUE TITLE
error compilation and build Jenkins

### ISSUE THREAD

**Issue by jjbserna** [arkon/ng-sidebar#208]
Hello everyone who contributes to this project, today after the last update I have presented problems in jenkins for its construction I was working on the "ng-sidebar" version: "^ 9.3.0", I get the next error. 

```
ERROR in node_modules/ng-sidebar/lib_commonjs/sidebar-container.component.d.ts.SidebarContainer.html(6,7): : Property '_onBackdropClicked' does not exist on type 'SidebarContainer'. Did you mean 'onBackdropClicked'?
node_modules/ng-sidebar/lib_commonjs/sidebar-container.component.d.ts.SidebarContainer.html(13,7): : Property '_getContentStyle' does not exist on type 'SidebarContainer'.
node_modules/ng-sidebar/lib_commonjs/sidebar.component.d.ts.Sidebar.html(11,7): : Property '_getStyle' does not exist on type 'Sidebar'.
node_modules/ng-sidebar/lib_commonjs/sidebar.component.d.ts.Sidebar.html(7,7): : Property '_isDocked' does not exist on type 'Sidebar'.
node_modules/ng-sidebar/lib_commonjs/sidebar.component.d.ts.Sidebar.html(8,7): : Property '_isInert' does not exist on type 'Sidebar'.

```
how can I fix it, what should I do to make it work, I was working on the "ng-sidebar" version: "^ 9.3.0", yesterday it was built well and today after the update I don't know what happened.

Help me Arkon

**Comment by zhoueric** [comment]
Same issue here. Compiling on Angular 8.2 gets the same errors.

**Comment by zhoueric** [comment]
i did a revert for now, which seems to work:
`npm install ng-sidebar@9.3.0 --save`

**Comment by arkon** [comment]
Ugh, I messed it up again. Try v9.4.2.

**Comment by zhoueric** [comment]
Works 9.4.2 :)

**Comment by jjbserna** [comment]
with 9.4.2 the same thing happens, it does not change the error, I tried all the versions until 9.0.0 and it generates the same error ...

help us Arkon

**Comment by jjbserna** [comment]
i will try again

**Comment by jjbserna** [comment]
Thanks a lot Arkon, it works again.
